WIP : Fitur Form Registrasi Reservasi Baru
jabardigitalservice/reservasi-commandcenter-microsite pull request #3
Opened 2021-03-12 08:57 UTC by maulanayuseph

**Task**
- Sebagai Masyarakat, saya dapat membuat reservasi kunjungan baru

**Changes**

- Pembuatan pages form reservasi
- Penambahan validation untuk input field
- Pembuatan halaman depan reservasi
- Penambahan file css

**Notes**
- Styling belum selesai 100%
- URL API masih hardcode, belum menggunakan env

**Preview**
![screencapture-localhost-3000-2021-03-12-15_53_15 (1)](https://user-images.githubusercontent.com/9844224/110916218-27e46f00-834b-11eb-8bde-e59c8ec3cfd3.png)

![screencapture-localhost-3000-reservasi-2021-03-12-15_53_26](https://user-images.githubusercontent.com/9844224/110916236-2adf5f80-834b-11eb-8e19-1ca3dc37a377.png)

2021-03-15 02:39 UTC, Arif9878 commented on yarn.lock
> +"@babel/code-frame@^7.12.13":
yarn lock maupun package lock kalau tidak di butuh tidak di push gpp

2021-03-15 02:39 UTC, Arif9878 commented on pages/reservasi/index.vue
> +      formatDate (date) {
coba tanya ke temen lain apakah fungsi formate date sudah di buat fungsi global

2021-03-15 02:39 UTC, Arif9878 commented on pages/reservasi/index.vue
> +      tanggalKunjungan: new Date().toISOString().substr(0, 10),
untuk state, props maupun method bahasanya bisa di seragamkan bahasa inggris atau bahasa indonesia.

2021-03-15 02:39 UTC, Arif9878 commented on pages/reservasi/index.vue
> +                :rules="[v => !!v || 'Kamu harus menyetujui syarat dan ketentuan yang berlaku!']"
yang lain dibuat rules di state kenapa ini tidak?

2021-03-15 02:39 UTC, Arif9878 commented on assets/css/main.css
> +.qs-welcome {
coba baca https://vuetifyjs.com/en/styles/text-and-typography/#font-emphasis sudah ada typography jadi mungkin tidak perlu buat class baru

2021-03-15 03:10 UTC, maulanayuseph commented on yarn.lock
> +"@babel/code-frame@^7.12.13":
oke siap mas..

2021-03-15 03:47 UTC, maulanayuseph commented on pages/reservasi/index.vue
> +      tanggalKunjungan: new Date().toISOString().substr(0, 10),
baik mas nanti diseragamkan

2021-03-15 03:48 UTC, maulanayuseph commented on assets/css/main.css
> +.qs-welcome {
siap trims referensinya

2021-03-15 04:54 UTC, bangunbagustapa requested changes
Form validation

2021-03-15 04:54 UTC, bangunbagustapa commented on pages/reservasi/index.vue
> +                required
Untuk field nama organisasi sifatnya optional.

2021-03-15 04:54 UTC, bangunbagustapa commented on pages/reservasi/index.vue
> +                required
Ini juga, sifatnya optional.

2021-03-15 05:36 UTC, maulanayuseph commented on pages/reservasi/index.vue
> +                required
iya sip kang

2021-03-15 05:43 UTC, adzharamrullah commented on pages/reservasi/index.vue
> +                  alert('masuk')
bisa dikasih lib toast atau notify ya untuk response successnya

2021-03-15 07:12 UTC, maulanayuseph commented on pages/reservasi/index.vue
> +                  alert('masuk')
baik kang nanti di install

2021-03-15 07:29 UTC, Arif9878 commented on pages/reservasi/index.vue
> +              postData.push(
ini kenapa satu form data pakai push trus bawahnya get index ke 0 ```postData[0]```

2021-03-16 03:29 UTC, maruf12 commented on pages/reservasi/index.vue
> +      tanggalKunjungan: new Date().toISOString().substr(0, 10),
@maulanayuseph penamaan varible atau function pakai bahasa inggris aja ya. Ini ada guideline juga buat penamaan varible disini:
https://wiki.digitalservice.id/doc/frontend-guides-U0GLTBXzCb

2021-03-17 00:41 UTC, maulanayuseph commented on pages/reservasi/index.vue
> +      tanggalKunjungan: new Date().toISOString().substr(0, 10),
sudah di update
cc : @maruf12 @Arif9878

2021-03-17 01:20 UTC, bangunbagustapa approved these changes

2021-03-17 04:47 UTC, yoslie commented on pages/index.vue
> +    </v-col>
indentation nya mang bisa konsisten masih banyak yg spasi 2, spasi 4, spasi 6 mungkin kalau gasalah liat,

kalau tdk salah kita komit pakai spasi 2 kan ya untuk indentasi?
cc: @adrianpdm @Arif9878 @maruf12 @adzharamrullah

2021-03-17 06:03 UTC, maulanayuseph commented on pages/index.vue
> +    </v-col>
@yoslie oh yaa kedepannya akan dikonsistensikan lagi untuk indentasi nya

2021-03-17 06:06 UTC, maulanayuseph commented on pages/index.vue
> +    </v-col>
apa ada settingan khusus di editor soalnya dulu pakai pretier mungkin ada perubahan dari sana sampai workhop bahasan editor langsung di uninstal

2021-03-18 08:08 UTC, adzharamrullah approved these changes

2021-03-18 08:12 UTC, Ibwedagama approved these changes

2021-03-18 08:14 UTC, maulanayuseph commented on pages/index.vue
> +    </v-col>
@yoslie untuk indentasi spasi sudah dirubah di perubahan baru minta feedback nya

2021-03-18 08:54 UTC, maruf12 commented on pages/reservasi/index.vue
> +      var dateNow = new Date();
@maulanayuseph ini kenapa menggunakan var?

2021-03-18 12:28 UTC, maulanayuseph commented on pages/reservasi/index.vue
> +      var dateNow = new Date();
terbiasa pakai var kalau hanya untuk 1 kali pemanggilan kang @maruf12

2021-03-19 00:48 UTC, yoslie approved these changes

2021-03-19 00:49 UTC, merged